name: etl

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1-5"

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Get job ID
        id: job_id
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          JOB_ID=$(gh api \
            /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs \
            --jq '.jobs[0].id')
          echo "job_id=$JOB_ID" >> "$GITHUB_OUTPUT"
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction
      - name: Run ETL
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PWD: ${{ secrets.EMAIL_PWD }}
          EMAIL_IMAP: ${{ secrets.EMAIL_IMAP }}
        run: |
          source .venv/bin/activate
          task etl
      - name: Workflow failure notification
        uses: peter-evans/create-issue-from-file@v6
        if: failure()
        env:
          RUNID: ${{ github.run_id }}
          JOBID: ${{ steps.job_id.outputs.job_id }}
        with:
          title: Sync template workflow failed on ${{ steps.date_step.outputs.now }}
          content-filepath: .github/etl_failure.md
